[package]
name = "tool"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tool"
path = "src/main.rs"

[dependencies]
reqwest = {version="0.11", features=["blocking","json","stream"]}
scraper = "0.13.0"
tokio = {version="1", features=["full"]}
