FROM fastapi-py39

RUN pip3 install FastAPI
#RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
RUN pip3 install torch torchvision torchaudio
COPY ./app /app