FROM python:3.9-alpine

# Installing packages
RUN apk update 
RUN pip install pipenv

RUN apk add --no-cache --virtual .build-deps gcc musl-dev unixodbc-dev g++

# 安裝 Python 依賴庫
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 複製應用程式代碼到容器內
COPY bootstrap.sh ./
COPY . .

EXPOSE 5000

ENTRYPOINT ["/app/bootstrap.sh"]
