//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TSQL.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TSQLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ITSQLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TSQLParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] TSQLParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TSQLParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] TSQLParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TSQLParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectStatement([NotNull] TSQLParser.SelectStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TSQLParser.selectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectStatement([NotNull] TSQLParser.SelectStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TSQLParser.selectColumnList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectColumnList([NotNull] TSQLParser.SelectColumnListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TSQLParser.selectColumnList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectColumnList([NotNull] TSQLParser.SelectColumnListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TSQLParser.selectColumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectColumn([NotNull] TSQLParser.SelectColumnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TSQLParser.selectColumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectColumn([NotNull] TSQLParser.SelectColumnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TSQLParser.fromClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFromClause([NotNull] TSQLParser.FromClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TSQLParser.fromClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFromClause([NotNull] TSQLParser.FromClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TSQLParser.tableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableReference([NotNull] TSQLParser.TableReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TSQLParser.tableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableReference([NotNull] TSQLParser.TableReferenceContext context);
}
