version: '3.3'
services:
  mysql:
    container_name: mysql_gpt_db
    build:
      context: ./
      dockerfile: mysql-docker.yml
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql_gpt_db
      - PMA_PORT=3306

  qdrant:
    container_name: qdrant_gpt_db
    image: qdrant/qdrant
    restart: always
    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"