FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["SqlLocalDataTests/SqlLocalDataTests.csproj", "SqlLocalDataTests/"]
COPY ["T1.SqlLocalData/T1.SqlLocalData.csproj", "T1.SqlLocalData/"]
RUN dotnet restore "SqlLocalDataTests/SqlLocalDataTests.csproj"
COPY . .
WORKDIR "/src/SqlLocalDataTests"
RUN dotnet build "SqlLocalDataTests.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SqlLocalDataTests.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "test", "SqlLocalDataTests.dll"]