#pragma warning disable 1591 // publicly visible type or member must be documented
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the T1.SourceGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
