//<auto-generated>
using System.Text;
using System.Text.Json;

namespace T1.SourceGenerator.Attributes;

internal partial class WebApiClient
{
    private HttpClient _httpClient;

    public WebApiClient(IHttpClientFactory httpClientFactory)
    {
        InitHttp(httpClientFactory);
        //<generate code: ctor/>
    }

    public TimeSpan Timeout { get; set; } = TimeSpan.FromSeconds(30);

    //<generate code: properties/>

    public string BaseUrl { get; set; }

    public async Task<TResp?> PostDataAsync<TResp>(string apiPath, object? data = null)
    {
        var requestUri = new Uri(BaseUrl + apiPath);
        var response = await _httpClient.PostAsync(requestUri, ToJsonContent(data));
        response.EnsureSuccessStatusCode();
        var result = await response.Content.ReadAsStringAsync();
        return Deserialize<TResp>(result);
    }

    private StringContent ToJsonContent(object? data)
    {
        return new StringContent(ToJsonStr(data), Encoding.UTF8, "application/json");
    }

    private string ToJsonStr(object? data)
    {
        var requestJson = "{}";
        if (data != null) requestJson = SerializeObject(data);
        return requestJson;
    }

    public async Task PostVoidAsync(string apiPath, object? data = null)
    {
        var requestUri = new Uri(BaseUrl + apiPath);
        var response = await _httpClient.PostAsync(requestUri, ToJsonContent(data));
        response.EnsureSuccessStatusCode();
    }

    public virtual string SerializeObject(object obj)
    {
        return JsonSerializer.Serialize(obj);
    }

    public virtual T? Deserialize<T>(string json)
    {
        return JsonSerializer.Deserialize<T>(json);
    }

    protected virtual void InitHttp(IHttpClientFactory httpClientFactory)
    {
        _httpClient = httpClientFactory.CreateClient();
    }
}