version: '3.4'

services:
  webportal:
    image: ${DOCKER_REGISTRY-}webportal
    build:
      context: .
      dockerfile: WebPortal/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - website1
      - website2

  website1:
    image: ${DOCKER_REGISTRY-}website1
    build:
      context: .
      dockerfile: WebSite1/Dockerfile
    ports:
      - "5001:80"

  website2:
    image: ${DOCKER_REGISTRY-}website2
    build:
      context: .
      dockerfile: WebSite2/Dockerfile
    ports:
      - "5002:80"
