namespace T1.SqlSharp.Expressions;

public enum SqlType
{
    CreateTable,
    ColumnDefinition,
    Constraint,
    ConstraintDefaultValue,
    ComputedColumn,
    DataType,
    DataSize,
    TableForeignKey,
    WithToggle,
    Identity,
    Select,
    Field,
    IntValue,
    ParameterValue,
    AddExtendedProperty,
    String,
    Token,
    TopClause,
    JoinCondition,
    TableSource,
    Function,
    Condition,
    SearchCondition,
    Hint,
    Group,
    Null,
    OrderByClause,
    OrderByColumn,
    Case,
    CaseWhen,
    AsExpr
}