//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TsqlParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace T1.SqlDom.Tsql {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TsqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ITsqlParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_statement([NotNull] TsqlParser.Select_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.top_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTop_clause([NotNull] TsqlParser.Top_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.top_count"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTop_count([NotNull] TsqlParser.Top_countContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.column_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_elem([NotNull] TsqlParser.Column_elemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.full_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFull_column_name([NotNull] TsqlParser.Full_column_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.select_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_list([NotNull] TsqlParser.Select_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.id_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId_([NotNull] TsqlParser.Id_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.as_column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAs_column_alias([NotNull] TsqlParser.As_column_aliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TsqlParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_alias([NotNull] TsqlParser.Column_aliasContext context);
}
} // namespace T1.SqlDom.Tsql
