//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TsqlParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace T1.SqlDom.Tsql {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITsqlParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class TsqlParserBaseListener : ITsqlParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.select_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_statement([NotNull] TsqlParser.Select_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.select_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_statement([NotNull] TsqlParser.Select_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.top_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_clause([NotNull] TsqlParser.Top_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.top_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_clause([NotNull] TsqlParser.Top_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.top_count"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_count([NotNull] TsqlParser.Top_countContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.top_count"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_count([NotNull] TsqlParser.Top_countContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.column_elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_elem([NotNull] TsqlParser.Column_elemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.column_elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_elem([NotNull] TsqlParser.Column_elemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.full_column_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFull_column_name([NotNull] TsqlParser.Full_column_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.full_column_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFull_column_name([NotNull] TsqlParser.Full_column_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.select_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_list([NotNull] TsqlParser.Select_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.select_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_list([NotNull] TsqlParser.Select_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.id_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId_([NotNull] TsqlParser.Id_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.id_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId_([NotNull] TsqlParser.Id_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.as_column_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAs_column_alias([NotNull] TsqlParser.As_column_aliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.as_column_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAs_column_alias([NotNull] TsqlParser.As_column_aliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TsqlParser.column_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_alias([NotNull] TsqlParser.Column_aliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TsqlParser.column_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_alias([NotNull] TsqlParser.Column_aliasContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace T1.SqlDom.Tsql
